# Pandas and Numpy

In [1]:
import numpy as np
import pandas as pd

products = ['Mobile', 'Laptop', 'AC', 'Fridge', 'TV', 'Washing Machine']
prices =   [25000,    55000,    40000, 35000,   30000,  45000]
stock =    [50,       30,       20,    15,       25,     10]
sold =     [30,       20,       15,    10,       18,     7]

In [2]:
prices_array = np.array(prices)
stock_array = np.array(stock)
sold_array = np.array(sold)

print(prices_array)
print(stock_array)
print(sold_array)
# problem - 01
inventory = prices_array * stock_array
print(inventory)
# Problem - 02
remaining = stock_array - sold_array
print(remaining)
# Problem - 03
df = pd.DataFrame({
    "Products" : products,
    "Prices" : prices_array,
    "Stock" : stock,
    "Sold" : sold
})
print(df[df["Prices"] > 35000])

df["remaining"] = stock_array - sold_array
print(df)

[25000 55000 40000 35000 30000 45000]
[50 30 20 15 25 10]
[30 20 15 10 18  7]
[1250000 1650000  800000  525000  750000  450000]
[20 10  5  5  7  3]
          Products  Prices  Stock  Sold
1           Laptop   55000     30    20
2               AC   40000     20    15
5  Washing Machine   45000     10     7
          Products  Prices  Stock  Sold  remaining
0           Mobile   25000     50    30         20
1           Laptop   55000     30    20         10
2               AC   40000     20    15          5
3           Fridge   35000     15    10          5
4               TV   30000     25    18          7
5  Washing Machine   45000     10     7          3


In [3]:
import numpy as np
import pandas as pd

products = ['Mobile', 'Laptop', 'AC', 'Fridge', 'TV', 'Washing Machine']
prices =   [25000,    55000,    40000, 35000,   30000,  45000]
stock =    [50,       30,       20,    15,       25,     10]
sold =     [30,       20,       15,    10,       18,     7]
ratings =  [4.5,      4.2,      3.8,   4.0,     4.7,    3.5]

df = pd.DataFrame({
    'Product': products,
    'Price': prices,
    'Stock': stock,
    'Sold': sold,
    'Rating': ratings
})

In [6]:
ratings_array = np.array(ratings)
mask = ratings_array > 4.0
print(mask)

# filtered
filtered = ratings_array[mask]
print(filtered)

[ True  True False False  True False]
[4.5 4.2 4.7]


In [8]:
# where class
discount = np.where(prices_array > 35000, prices_array * 0.85, prices_array)
print(discount)

[25000. 46750. 34000. 35000. 30000. 38250.]


In [9]:
df_sorted = df.sort_values(by="Price", ascending=False)
print(df_sorted)

           Product  Price  Stock  Sold  Rating
1           Laptop  55000     30    20     4.2
5  Washing Machine  45000     10     7     3.5
2               AC  40000     20    15     3.8
3           Fridge  35000     15    10     4.0
4               TV  30000     25    18     4.7
0           Mobile  25000     50    30     4.5


In [10]:
nlargest = df.nlargest(3, "Rating")[["Product", "Rating"]]
print(nlargest)

  Product  Rating
4      TV     4.7
0  Mobile     4.5
1  Laptop     4.2


In [11]:
df["Status"] = np.select([df["Sold"] >= 20, df["Sold"] >= 10], ["Hot Selling", "Normal"], default="Slow")
print(df[["Product", "Sold", "Status"]])

           Product  Sold       Status
0           Mobile    30  Hot Selling
1           Laptop    20  Hot Selling
2               AC    15       Normal
3           Fridge    10       Normal
4               TV    18       Normal
5  Washing Machine     7         Slow
