# Pandas and Numpy

In [1]:
import numpy as np
import pandas as pd

products = ['Mobile', 'Laptop', 'AC', 'Fridge', 'TV', 'Washing Machine']
prices =   [25000,    55000,    40000, 35000,   30000,  45000]
stock =    [50,       30,       20,    15,       25,     10]
sold =     [30,       20,       15,    10,       18,     7]

In [13]:
prices_array = np.array(prices)
stock_array = np.array(stock)
sold_array = np.array(sold)

print(prices_array)
print(stock_array)
print(sold_array)
# problem - 01
inventory = prices_array * stock_array
print(inventory)
# Problem - 02
remaining = stock_array - sold_array
print(remaining)
# Problem - 03
df = pd.DataFrame({
    "Products" : products,
    "Prices" : prices_array,
    "Stock" : stock,
    "Sold" : sold
})
print(df[df["Prices"] > 35000])

df["remaining"] = stock_array - sold_array
print(df)

[25000 55000 40000 35000 30000 45000]
[50 30 20 15 25 10]
[30 20 15 10 18  7]
[1250000 1650000  800000  525000  750000  450000]
[20 10  5  5  7  3]
          Products  Prices  Stock  Sold
1           Laptop   55000     30    20
2               AC   40000     20    15
5  Washing Machine   45000     10     7
          Products  Prices  Stock  Sold  remaining
0           Mobile   25000     50    30         20
1           Laptop   55000     30    20         10
2               AC   40000     20    15          5
3           Fridge   35000     15    10          5
4               TV   30000     25    18          7
5  Washing Machine   45000     10     7          3


In [14]:
import numpy as np
import pandas as pd

products = ['Mobile', 'Laptop', 'AC', 'Fridge', 'TV', 'Washing Machine']
prices =   [25000,    55000,    40000, 35000,   30000,  45000]
stock =    [50,       30,       20,    15,       25,     10]
sold =     [30,       20,       15,    10,       18,     7]
ratings =  [4.5,      4.2,      3.8,   4.0,     4.7,    3.5]

df = pd.DataFrame({
    'Product': products,
    'Price': prices,
    'Stock': stock,
    'Sold': sold,
    'Rating': ratings
})