In [2]:
print("Hello World")

Hello World


In [3]:
import numpy as np


In [4]:
one_d_array = np.array([1, 2, 3]) # 1D
two_d_array = np.array([[1, 2, 3], [4, 5, 6]]) # 2D
force_datatype = np.array([1, 2, 3], dtype=float) # force dtype

In [5]:
print(one_d_array)
print(two_d_array)
print(force_datatype)

[1 2 3]
[[1 2 3]
 [4 5 6]]
[1. 2. 3.]


# Built-in generators

In [6]:
zeros = np.zeros((3, 4))
ones = np.ones((2, 3))
constant = np.full((2, 2), 7)
empty = np.empty((2, 2))
identity_matrix = np.eye(4)
identity_matrix_1 = np.identity(4)


In [7]:
print(zeros)
print(ones)
print(constant)
print(empty)
print(identity_matrix)
print(identity_matrix_1)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[7 7]
 [7 7]]
[[1.16364022e-313 0.00000000e+000]
 [6.59737730e-310 1.02124020e+277]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


# Ranges & sequences

In [8]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [9]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

# Random arrays

In [10]:
np.random.rand(3, 2)

array([[0.60309754, 0.94530429],
       [0.03998019, 0.2924716 ],
       [0.95867642, 0.07121247]])

In [11]:
np.random.randn(3, 2)

array([[-0.06392696, -0.6694458 ],
       [ 0.60979444,  0.50704724],
       [ 0.61545122,  2.64927206]])

In [12]:
np.random.randint(0, 10, (3, 3))

array([[2, 6, 9],
       [9, 5, 6],
       [1, 2, 6]])

In [13]:
np.random.seed(42)

In [14]:
np.random.choice([1, 2, 3], size=5, replace=True)

array([3, 1, 3, 3, 1])

In [15]:
rng = np.random.default_rng(seed=42)
rng.random((3, 3))
rng.integers(0, 10, size=5)

array([8, 4, 5, 3, 1])

# Copying vs generating like another array

In [16]:
list = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
arr = np.array(list)


In [17]:
np.zeros_like(arr)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [18]:
np.ones_like(arr)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [19]:
np.full_like(arr, 5)

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [20]:
arr.copy()

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# Array Attributes (inspecting an array)

In [21]:
arr.ndim

2

In [22]:
arr.shape

(3, 3)

In [23]:
arr.size

9

In [24]:
arr.dtype

dtype('int64')

In [25]:
arr.itemsize

8

In [26]:
arr.nbytes # total bytes = size * itemsize

72

In [27]:
arr.T # transpose

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [28]:
arr.data

In [29]:
arr.astype(np.float32)

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]], dtype=float32)

In [30]:
arr.astype(np.int32)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int32)

# Indexing & Slicing

In [31]:
arr[0] # first element


array([1, 2, 3])

In [32]:
arr[-1] # last element

array([7, 8, 9])

In [33]:
arr[0:4]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [34]:
arr[:, 1]       # entire column 1

array([2, 5, 8])

In [35]:
arr[0:2, 1:3]   # sub-matrix

array([[2, 3],
       [5, 6]])

In [36]:
arr[[0, 2]]

array([[1, 2, 3],
       [7, 8, 9]])

In [37]:
arr[[0, 1], [1, 2]]

array([2, 6])

# Boolean masking

In [38]:
arr[arr > 5]

array([6, 7, 8, 9])

In [39]:
arr[(arr > 2) & (arr < 8)]

array([3, 4, 5, 6, 7])

In [40]:
arr[arr > 5] = 0

In [41]:
arr

array([[1, 2, 3],
       [4, 5, 0],
       [0, 0, 0]])

In [42]:
np.where(arr > 5, 1, 0)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

# Reshaping & Manipulating Shape

In [43]:
arr.reshape(-1, 1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [0],
       [0],
       [0],
       [0]])

In [44]:
arr.flatten()

array([1, 2, 3, 4, 5, 0, 0, 0, 0])

In [45]:
arr.ravel()

array([1, 2, 3, 4, 5, 0, 0, 0, 0])

In [46]:
arr.transpose()

array([[1, 4, 0],
       [2, 5, 0],
       [3, 0, 0]])

In [47]:
np.expand_dims([1, 2, 3], axis=0)

array([[1, 2, 3]])

# Joining arrays

In [48]:
a = [1, 2, 3]
b = [4, 5, 6]

In [49]:
np.concatenate([a, b], axis=0)

array([1, 2, 3, 4, 5, 6])

In [50]:
np.vstack([a, b])

array([[1, 2, 3],
       [4, 5, 6]])

In [51]:
np.hstack([a, b])

array([1, 2, 3, 4, 5, 6])

In [52]:
arr_1 = np.column_stack([a, b])
arr_1

array([[1, 4],
       [2, 5],
       [3, 6]])

# Splitting arrays

In [53]:
np.split(arr, 3)

[array([[1, 2, 3]]), array([[4, 5, 0]]), array([[0, 0, 0]])]

In [54]:
np.hsplit(arr, 3)

[array([[1],
        [4],
        [0]]),
 array([[2],
        [5],
        [0]]),
 array([[3],
        [0],
        [0]])]

In [55]:
np.vsplit(arr, 3)

[array([[1, 2, 3]]), array([[4, 5, 0]]), array([[0, 0, 0]])]

# Array Operations (Vectorized Math)

a + b, a - b, a * b, a / b, a // b, a % b, a ** 2

np.add(a, b), np.subtract(a, b), np.multiply(a, b), np.divide(a, b)

In [56]:
print(a)
print(b)

[1, 2, 3]
[4, 5, 6]


In [57]:
np.add(a, b)

array([5, 7, 9])

In [58]:
np.subtract(a, b)

array([-3, -3, -3])

In [59]:
np.divide(b, a)

array([4. , 2.5, 2. ])

In [60]:
np.multiply(a, b)

array([ 4, 10, 18])

# Universal functions (ufuncs) — element-wise, vectorized

In [63]:
np.sqrt(a)

array([1.        , 1.41421356, 1.73205081])

In [64]:
np.exp(a)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [65]:
np.log(a)

array([0.        , 0.69314718, 1.09861229])

In [66]:
np.log10(a)

array([0.        , 0.30103   , 0.47712125])

In [67]:
np.sin(a)

array([0.84147098, 0.90929743, 0.14112001])

# Comparison operators (return boolean arrays)

In [ ]:
np.array_equal(a, b) # True/False for whole arrays
np.allclose(a, b)  # tolerant float comparison

False

# Aggregate / reduction functions

In [74]:
arr.sum(axis=0) # column-wise sum (2D)


array([5, 7, 3])

In [76]:
arr

array([[1, 2, 3],
       [4, 5, 0],
       [0, 0, 0]])

In [77]:
arr.sum(axis=1) # column-wise sum (2D)

array([6, 9, 0])

In [ ]:
arr.argmax()

np.int64(4)

In [80]:
np.median(arr)

np.float64(1.0)

# Broadcasting

In [82]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([10,20,30])

In [83]:
a + b

array([[11, 22, 33],
       [14, 25, 36]])

In [84]:
c = np.array([[1],[2]])

In [85]:
a + c

array([[2, 3, 4],
       [6, 7, 8]])

# Handling Missing / Special Values


In [88]:
np.nan

nan

In [91]:
np.isnan(a).sum()

np.int64(0)

In [92]:
np.nan_to_num(b)

array([10, 20, 30])

In [93]:
np.isinf(a)

array([[False, False, False],
       [False, False, False]])

In [94]:
np.isfinite(a)

array([[ True,  True,  True],
       [ True,  True,  True]])

# Sorting, Searching & Set Operations

In [95]:
arr = [7, 2, 0]

In [96]:
np.sort(arr)

array([0, 2, 7])

In [97]:
np.argsort(arr)

array([2, 1, 0])

In [99]:
np.searchsorted(arr, 7)
arr

[7, 2, 0]

In [105]:
np.where(a == 5)

(array([1]), array([1]))

# Iterating Over Arrays

In [107]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [108]:
arr

[7, 2, 0]

In [106]:
for x in a:
    print(x)

[1 2 3]
[4 5 6]


In [109]:
for x in np.nditer(a):
    print(x)

1
2
3
4
5
6


In [110]:
for idx, value in np.ndenumerate(a):
    print(idx, value)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(1, 0) 4
(1, 1) 5
(1, 2) 6


In [112]:
np.tile(arr, 3)

array([7, 2, 0, 7, 2, 0, 7, 2, 0])

In [114]:
np.tile(arr, (2, 1))

array([[7, 2, 0],
       [7, 2, 0]])

In [116]:
np.repeat(arr, 3) # repeate each element 3 times

array([7, 7, 7, 2, 2, 2, 0, 0, 0])

In [121]:
np.repeat(a, 3, axis=1)

array([[1, 1, 1, 2, 2, 2, 3, 3, 3],
       [4, 4, 4, 5, 5, 5, 6, 6, 6]])

In [122]:
np.save("arr.npy", arr)

In [123]:
np.load('arr.npy')

array([7, 2, 0])