In [1]:
print("fbkdj")

fbkdj


In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# Leetcode 

In [20]:
L = [1,2, 3, 4]



In [21]:
def func(L):
    new_list = []
    for i in range(len(L)):
        prod = 1
        for idx, val in enumerate(L):
            if(idx == i):
                continue
            else:
                prod *= val
        
        new_list.append(prod)
    return new_list
        
        
func(L)
        

[24, 12, 8, 6]

In [34]:
students = [
    {"name": "Muzzamal", "marks": 30},
    {"name": "Ali", "marks": 45},
    {"name": "Ahmed", "marks": 67},
    {"name": "Hassan", "marks": 82},
    {"name": "Usman", "marks": 55},
    {"name": "Hamza", "marks": 91},
    {"name": "Bilal", "marks": 38},
    {"name": "Saad", "marks": 74},
    {"name": "Zain", "marks": 63},
    {"name": "Talha", "marks": 88}
]

In [59]:
for i in students:
    for j, k in i.items():
        print(k)

Muzzamal
30
Ali
45
Ahmed
67
Hassan
82
Usman
55
Hamza
91
Bilal
38
Saad
74
Zain
63
Talha
88


In [62]:
import sklearn
print(sklearn.__version__)

1.6.1


In [65]:
from sklearn.preprocessing import LabelEncoder

colors =["red", "blue", "green"]
endoded = LabelEncoder()

encoded_colors = endoded.fit_transform(colors)
encoded_colors

array([2, 0, 1])

In [ ]:
from sklearn.preprocessing import OneHotEncoder

ohe = OneHotEncoder()

In [66]:
import pandas as pd

data = {
    "Student_ID": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    "City": [
        "Lahore", "Karachi", "Islamabad", "Lahore", "Faisalabad",
        "Karachi", "Lahore", "Islamabad", "Faisalabad", "Karachi"
    ],
    "Gender": [
        "Male", "Female", "Male", "Female", "Male",
        "Male", "Female", "Female", "Male", "Female"
    ],
    "Education": [
        "BS", "BS", "MS", "BS", "BS",
        "MS", "MS", "BS", "MS", "BS"
    ],
    "Department": [
        "IT", "CS", "IT", "SE", "CS",
        "SE", "IT", "CS", "IT", "SE"
    ],
    "Age": [21, 22, 24, 21, 23, 25, 24, 22, 26, 21],
    "GPA": [3.2, 3.6, 3.8, 3.4, 3.1, 3.7, 3.9, 3.5, 3.3, 3.8]
}

df = pd.DataFrame(data)

df

,Student_ID,City,Gender,Education,Department,Age,GPA
0,1,Lahore,Male,BS,IT,21,3.2
1,2,Karachi,Female,BS,CS,22,3.6
2,3,Islamabad,Male,MS,IT,24,3.8
3,4,Lahore,Female,BS,SE,21,3.4
4,5,Faisalabad,Male,BS,CS,23,3.1
5,6,Karachi,Male,MS,SE,25,3.7
6,7,Lahore,Female,MS,IT,24,3.9
7,8,Islamabad,Female,BS,CS,22,3.5
8,9,Faisalabad,Male,MS,IT,26,3.3
9,10,Karachi,Female,BS,SE,21,3.8


In [88]:
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder()

encoded = ohe.fit_transform( df[["Gender"]])
print(encoded.toarray())
print(df)


[[0. 1.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [1. 0.]]
   Student_ID        City  Gender Education Department  Age  GPA
0           1      Lahore    Male        BS         IT   21  3.2
1           2     Karachi  Female        BS         CS   22  3.6
2           3   Islamabad    Male        MS         IT   24  3.8
3           4      Lahore  Female        BS         SE   21  3.4
4           5  Faisalabad    Male        BS         CS   23  3.1
5           6     Karachi    Male        MS         SE   25  3.7
6           7      Lahore  Female        MS         IT   24  3.9
7           8   Islamabad  Female        BS         CS   22  3.5
8           9  Faisalabad    Male        MS         IT   26  3.3
9          10     Karachi  Female        BS         SE   21  3.8


In [89]:
import pandas as pd

data = {
    "Student": ["Ali", "Sara", "Ahmed", "Ayesha", "Bilal", "Hassan", "Zain", "Fatima"],
    "Gender": ["Male", "Female", "Male", "Female", "Male", "Male", "Male", "Female"],
    "City": ["Lahore", "Karachi", "Islamabad", "Lahore", "Karachi", "Multan", "Islamabad", "Lahore"],
    "Education": ["Bachelor", "Master", "Bachelor", "PhD", "Master", "Bachelor", "PhD", "Master"],
    "Result": ["Pass", "Pass", "Fail", "Pass", "Fail", "Pass", "Pass", "Fail"]
}

df = pd.DataFrame(data)

print(df)

  Student  Gender       City Education Result
0     Ali    Male     Lahore  Bachelor   Pass
1    Sara  Female    Karachi    Master   Pass
2   Ahmed    Male  Islamabad  Bachelor   Fail
3  Ayesha  Female     Lahore       PhD   Pass
4   Bilal    Male    Karachi    Master   Fail
5  Hassan    Male     Multan  Bachelor   Pass
6    Zain    Male  Islamabad       PhD   Pass
7  Fatima  Female     Lahore    Master   Fail


In [90]:
import pandas as pd

data = {
    "Student": ["Ali", "Sara", "Ahmed", "Ayesha", "Bilal", "Hassan", "Zain", "Fatima"],
    "Study_Level": [
        "Low", "High", "Medium", "Excellent",
        "Medium", "Low", "High", "Excellent"
    ],
    "Performance": [
        "Poor", "Excellent", "Average", "Good",
        "Average", "Poor", "Good", "Excellent"
    ],
    "Satisfaction": [
        "Dissatisfied", "Satisfied", "Neutral", "Very Satisfied",
        "Neutral", "Dissatisfied", "Satisfied", "Very Satisfied"
    ]
}

df = pd.DataFrame(data)

print(df)

  Student Study_Level Performance    Satisfaction
0     Ali         Low        Poor    Dissatisfied
1    Sara        High   Excellent       Satisfied
2   Ahmed      Medium     Average         Neutral
3  Ayesha   Excellent        Good  Very Satisfied
4   Bilal      Medium     Average         Neutral
5  Hassan         Low        Poor    Dissatisfied
6    Zain        High        Good       Satisfied
7  Fatima   Excellent   Excellent  Very Satisfied


In [91]:
from sklearn.preprocessing import OrdinalEncoder

oe = OrdinalEncoder()

encoded = oe.fit_transform([["Excellent", 4], ["Medium", 3], ["High", 2], ["Low", 1]])
print(encoded)


[[0. 3.]
 [3. 2.]
 [1. 1.]
 [2. 0.]]
